version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: 'token list'
      include: 'scope'
    labels:
      - 'tokenlist'
      # Add default Kodiak `merge.automerge_label`
      #- 'automerge'
    allow:
      - dependency-name: 'sushi-sdk-ftm/packages/bentobox-sdk'
      - dependency-name: 'sushi-sdk-ftm/packages/chainlink-whitelist'
      - dependency-name: 'sushi-sdk-ftm/packages/core'
      - dependency-name: 'sushi-sdk-ftm/packages/core-sdk'
      - dependency-name: 'sushi-sdk-ftm/packages/default-token-list'
      - dependency-name: 'sushi-sdk-ftm/packages/kashi-sdk'
      - dependency-name: 'sushi-sdk-ftm/packages/limit-order-pair-list'
      - dependency-name: 'sushi-sdk-ftm/packages/limit-order-sdk'
      - dependency-name: 'sushi-sdk-ftm/packages/tines'
      - dependency-name: 'sushi-sdk-ftm/packages/trident'
      - dependency-name: 'sushi-sdk-ftm/packages/trident-sdk'
